### ISSUE TITLE
`session.addMessageListener` doesn't seem to work anymore.

### ISSUE THREAD

**Issue by madki** [googlecast/CastHelloText-chrome#15]
The v2 API still seems to supported according to the documentation. But the session.addMessageListener isn't being called when the receiver sends a message. Any idea what the issue is?

**Comment by entertailion** [comment]
If you believe this is a bug in the SDK, then file an issue: https://issuetracker.google.com/issues?q=componentid:190205%20status:open&s=modified_time:desc

**Comment by madki** [comment]
Hi @entertailion,

Seems the `sessionListener` passed to `ApiConfig` isn't called if a `onSuccess` function is passed to `requestSession`. Hence the `messageListener` was never getting added to the session. It's not a bug with the SDK. Just a small issue with the sample that was very hard to debug.

Removing a callback to `requestSession` or adding the code to initialize session there both seem to work.
